### ISSUE TITLE
CSS Squashing table data

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/docs#477] opened 2020-09-10 19:19 UTC
Hi,

On example doc's page: https://octobercms.com/docs/markup/function-form

See screenshot:

![image](https://user-images.githubusercontent.com/57409060/92789408-ba0eb900-f3a2-11ea-9aef-3d498a99b7e0.png)

Now if I over-ride the css we get this screenshot:

![image](https://user-images.githubusercontent.com/57409060/92789554-df9bc280-f3a2-11ea-8a3d-6494506e4058.png)

p.s. I'm in the middle of coding a large project, so if someone could create a pr for this that would be great.

**Comment by bennothommo** [comment] 2020-09-11 01:06
Duplicate of #476

**Closed by bennothommo** 2020-09-11 01:06 UTC

**Comment by ayumi-cloud** [comment] 2020-09-11 10:37
Opps my bad didn't see the dup. issue.
