### ISSUE TITLE
Correct and easy procedure to upgrade octobercms 1.0 to 1.1

### ISSUE THREAD

**Issue by zimudec** [octobercms/docs#488] opened 2020-10-14 18:06 UTC
I noticed that version 1.1 is already stable, which uses laravel 6.x which is the current LTS version under maintenance. I have installations of octobercms 1.0, but I have doubts about it, since it is not clear from documentation:

- What is the easiest and correct procedure to upgrade to version 1.1? https://octobercms.com/support/article/rn-11 <- Is this the only procedure?
- Is it necessary to manipulate a programmer's code to upgrade? or can it be done without it?
- Is the installations upgraded without composer from the backend system?
- For those who stay in version 1.0, although it continues to be maintained by octobercms, is it not a real risk due to the end of the maintenance of external libraries, especially laravel 5.5 since September 2020?
- How can you foresee possible incompatibilities with plugins and libraries due to the upgrade, before doing the upgrade?
- How can I do a clean installation of version 1.1?

**Comment by LukeTowers** [comment] 2020-10-14 18:56
Duplicate of #5314.

**Closed by LukeTowers** 2020-10-14 18:56 UTC
Labels: duplicate
